[project]
name = "PyMieSim"
version = "1.12.3"
description = "A package for light scattering computation."
documentation = 'https://pymiesim.readthedocs.io/'
platforms = ['unix', 'linux', 'osx']
readme = "README.rst"
url = 'https://github.com/MartinPdeS/PyMieSim'
requires-python = ">=3.10"
authors = [{ name="Martin Poinsinet de Sivry-Houle", email="martin.poinsinet.de.sivry@gmail.com"}]
classifiers = [
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: Implementation :: CPython',
    'Development Status :: 3 - Alpha',
    'Topic :: Scientific/Engineering :: Physics',
    'License :: OSI Approved :: MIT License',
    'Intended Audience :: Science/Research',
]
keywords = [
    "mie",
    "scattering",
    "backscatter",
    "sphere",
    "cylinder",
    "nanoparticle",
    "phase function",
    "efficiency",
    "rayleigh",
    "backscattering"
]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
    '-v',
    '-rA',
    '-rw'
]

testpaths = [
    "tests/detectors",
    "tests/scatterers",
    "tests/experiments",
    # "tests/gui",
    "tests/validation",
    "tests/extra"
]

minversion = 6.0

[tool.cibuildwheel]
build-frontend = "pip"
build-verbosity = 1
before-test = ""
test-command = "python -m pytest -rA {project}/tests --ignore={project}/tests/gui"
test-extras = ["testing"]

[tool.cibuildwheel.linux]
archs = ["x86_64"]
build = ["cp310-manylinux*", "cp311-manylinux*", "cp312-manylinux*"]
manylinux-x86_64-image = "manylinux2014"
repair-wheel-command = "auditwheel repair -w {dest_dir} {wheel}"

[tool.cibuildwheel.macos]
archs = ["arm64", "universal2", "x86_64"]
build = ["cp310-*", "cp311-*", "cp312-*"]
repair-wheel-command = "delocate-wheel -w {dest_dir} -v {wheel}"

[tool.cibuildwheel.windows]
archs = ["AMD64"]
build = ["cp310-*", "cp311-*", "cp312-*"]
