name: MacOS-x86_64-Workflow

permissions:
    contents: write

on:
    workflow_call:
        inputs:
            python_version_list:
                type: string
                required: false
                default: "['3.10']"


jobs:
    job_create_wheel:
        name: "Python ${{ matrix.python_version }}"
        runs-on: macos-latest
        strategy:
            fail-fast: false
            matrix:
                python_version: ${{ fromJson(inputs.python_version_list) }}
        steps:
          - name: "Checkout repository"
            uses: actions/checkout@v3
            with:
                submodules: true

          - uses: MartinPdeS/MPSActions/interpret_python_version@master
            with:
              python_version: ${{ matrix.python_version }}

          - name: Setup GNU Fortran
            uses: fortran-lang/setup-fortran@v1
            id: setup-fortran

          - name: "Build: Wheels"
            uses: pypa/cibuildwheel@v2.16.2
            with:
                output-dir: dist
            env:
                FC: /usr/local/bin/gfortran
                CIBW_BUILD: "${{ env.cp_python_version }}-macosx_x86_64"
                CIBW_ARCHS: "x86_64"
                CIBW_PLATFORM: "macos"
                CIBW_TEST_REQUIRES: ".[development]"
                CIBW_BUILD_VERBOSITY: 1
                MACOSX_DEPLOYMENT_TARGET: "10.13"
                _PYTHON_HOST_PLATFORM: "macosx-10.13-x86_64"
                CIBW_ENVIRONMENT_MACOS:
                    PROJ_WHEEL=true
                    PROJ_NETWORK=ON
                    MACOSX_DEPLOYMENT_TARGET=10.13
                CIBW_TEST_COMMAND: 'pytest -s {project}/tests'
                CIBW_BEFORE_BUILD: |
                    mkdir build ;
                    cd build ;
                    cmake -G"Unix Makefiles" -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DPYBIND11_PYTHON_VERSION=${{ matrix.python_version }}  ./.. ;
                    make install ;
                    cd ..


          - name: "Upload: Wheel"
            uses: actions/upload-artifact@v3
            with:
                name: "macos_x86_64_wheel_${{ env.cp_python_version }}"
                path: ./dist/*




# -
