name: MacOS-arm64-Workflow

permissions:
  contents: write

on:
  workflow_call:
    inputs:
      python_version:
        type: string
        required: false
        default: "['3.7']"


jobs:
  job_create_wheel_arm64:
    name: "Python ${{ matrix.python-version[1] }}-arm64"
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJson(inputs.python_version) }}
    steps:

      - name: "Checkout repository"
        uses: actions/checkout@v3
        with:
          submodules: true

      - uses: MartinPdeS/MPSActions/interpret_python_version@master
        with:
          python-version: ${{ matrix.python_version }}

      - name: "Set up Python${{ matrix.python-version[0] }}"
        run: |
           brew install python@${{ matrix.python-version[0] }}
           python${{ matrix.python-version[0] }} -m pip install -U pip pipx setuptools

      - name: Install cibuildwheel
        run: |
          python${{ matrix.python-version[0] }} -m pip install cibuildwheel==2.11.2

      - name: Build wheels
        run: |
          python${{ matrix.python-version[0] }} -m cibuildwheel --output-dir dist
        env:
          CIBW_BUILD: "${{ matrix.python-version[1] }}-macosx_arm64"
          CIBW_ARCHS: "arm64"
          CIBW_BEFORE_BUILD: 'mkdir build && cd build
                           && cmake -G"Unix Makefiles" -DPYBIND11_PYTHON_VERSION=${{ matrix.python-version[0] }}  ./..
                           && make install
                           && cd ..'
          CIBW_PLATFORM: "macos"
          CIBW_BUILD_VERBOSITY: 1
          _PYTHON_HOST_PLATFORM: "macosx-10.13-arm64"
          CIBW_ENVIRONMENT_MACOS:
            PROJ_WHEEL=true
            PROJ_NETWORK=ON
            MACOSX_DEPLOYMENT_TARGET=10.13
          CIBW_TEST_REQUIRES: ""
          CIBW_TEST_COMMAND: ''

      - name: "Upload: Wheel"
        uses: actions/upload-artifact@v3
        with:
          name: "macos_arm64_wheel_${{ matrix.python-version[1] }}"
          path: ./dist/*


  job_create_wheel_universal2:
    name: "Python ${{ matrix.python-version[1] }}-universal2"
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJson(inputs.python_version) }}
    steps:

      - name: "Checkout repository"
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: "Set up Python${{ matrix.python-version[0] }}"
        run: |
           brew install python@${{ matrix.python-version[0] }}
           python${{ matrix.python-version[0] }} -m pip install -U pip pipx setuptools

      - name: Install cibuildwheel
        run: |
          python${{ matrix.python-version[0] }} -m pip install cibuildwheel==2.11.2

      - name: Build wheels
        run: |
          python${{ matrix.python-version[0] }} -m cibuildwheel --output-dir dist
        env:
          CIBW_BUILD: "${{ matrix.python-version[1] }}-macosx_universal2"
          CIBW_ARCHS: "universal2"
          CIBW_PLATFORM: "macos"
          CIBW_BUILD_VERBOSITY: 1
          _PYTHON_HOST_PLATFORM: "macosx-10.13-universal2"
          CIBW_ENVIRONMENT_MACOS:
            PROJ_WHEEL=true
            PROJ_NETWORK=ON
            MACOSX_DEPLOYMENT_TARGET=10.13
          CIBW_TEST_REQUIRES: ""
          CIBW_TEST_COMMAND: ''

      - name: "Upload: Wheel"
        uses: actions/upload-artifact@v3
        with:
          name: "macos_universal2_wheel_${{ matrix.python-version[1] }}"
          path: ./dist/*

# -

