name: Windows-Workflow

permissions:
  contents: write

on:
  workflow_call:
    inputs:
      python_version_list:
        type: string
        required: false
        default: "['3.10']"

jobs:
  job_create_wheel:
    name: "Python ${{ matrix.python_version }}"
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: ${{ fromJson(inputs.python_version_list) }}

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
        with:
          submodules: true

      - uses: MartinPdeS/MPSActions/interpret_python_version@master
        with:
          python-version: ${{ matrix.python_version }}

      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-openmp
            mingw-w64-x86_64-ninja

      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: "Build: Wheels"
        uses: pypa/cibuildwheel@v2.16.2
        with:
          output-dir: dist
        env:
          CIBW_BUILD: "${{ env.cp_python_version }}-win_amd64"
          CIBW_TEST_REQUIRES: ".[development]"
          CIBW_BUILD_VERBOSITY: 1
          CIBW_ARCHS: "auto"
          CIBW_TEST_COMMAND: 'pytest -s {project}/tests'
          CIBW_BEFORE_BUILD: 'echo "C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/x86_64-w64-mingw32/lib/" >> $GITHUB_PATH
                           && mkdir build
                           && cd build
                           && cmake -G"Ninja" -DCMAKE_FIND_DEBUG_MODE=1 -DPYBIND11_PYTHON_VERSION=${{ matrix.python_version }}  ./..
                           && ninja
                           && cd ..
                           && python -m pip install .'

      - name: "Upload: Wheel"
        uses: actions/upload-artifact@v3
        with:
          name: "windows_wheel_python${{ env.PYTHON_CP_VERSION }}"
          path: ./dist/*




# -
