name: badge_deploy

# https://github.com/YannickJadoul/Parselmouth/blob/master/.github/workflows/wheels.yml
permissions:
  contents: write

on:
  workflow_call:
    inputs:
      python_version:
        type: string
        required: true
        default: '3.10'

jobs:
  deploy_badge:
    name: "Badge deploy"
    runs-on: ubuntu-latest
    steps:
      - uses: MartinPdeS/MPSActions/install_package_on_manylinux@master
        with:
          python_version: ${{ inputs.python_version }}
          package_name: PyMieSim

      - uses: MartinPdeS/MPSActions/compute_unittest_coverage@master
        with:
          auth: ${{ secrets.MPdS_gist_token }}
          gistID: 2cac8ebb51cd9ce07dc7a955648301d5

